### PR TITLE
append static to closure, add import for array_key_exists, replace de…

### PR DESCRIPTION
**Pull request by pavbis**
Deprecated assertion in StreamTest.

It also makes sence to update the phpunit version.
The version 7 is currently used.

### CODE REVIEW

**Comment by hollodotme** [comment]
I added some uncommitted changes to the 3.x-dev branch and updated the CI config.
Can you please rebase your branch on 3.x-dev.

**Comment by hollodotme** [comment]
I also updated all the tools in composer json, e.g. PHPUnit to v8

**Comment by pavbis** [comment]
> Can you please rebase your branch on 3.x-dev.

done.

**Comment by hollodotme** [comment]
Closing. Fixed it manually. Thanks anyway!

**Pull request closed without merging**
